name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: docker compose down

      - name: Deploy with Docker
        run: docker compose --profile prod up -d --build

      - name: Cleanup unused images
        run: docker image prune -f